CREATE TABLE T_ORDER_DETAILS (
    ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    UNIT_PRICE NUMERIC NOT NULL,
    UNIT_VAT NUMERIC NOT NULL,
    QUANTITY INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES T_PRODUCT(ID)
);